### ISSUE TITLE
Unable to send command to other server(spigot).

### ISSUE THREAD

**Issue by extremecat** [jingwenMC/MQEasy#1]
**spigot(L3) Run command**
> sendcmdtoserver L1 bc hello

**spigot(L1) Console**
`[20:36:58 WARN]: java.lang.IllegalStateException: Asynchronous command dispatch!
[20:36:58 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[20:36:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:801)
[20:36:58 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776)
[20:36:58 WARN]:        at cn.southplex.commandbridge.mode.MessageQueueMode.onReceiveNoReturn(MessageQueueMode.java:79)
[20:36:58 WARN]:        at top.jingwenmc.mqeasy.common.plugin.PluginManager.sendMessageToPlugin(PluginManager.java:35)
[20:36:58 WARN]:        at top.jingwenmc.mqeasy.common.messaging.MQEasyMessageListener.onMessage(MQEasyMessageListener.java:58)
[20:36:58 WARN]:        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1435)
[20:36:58 WARN]:        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131)
[20:36:58 WARN]:        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202)
[20:36:58 WARN]:        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
[20:36:58 WARN]:        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
[20:36:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:36:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:36:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[20:36:58 WARN]: ===============[MQEasy-Runtime-Error]===============
[20:36:58 WARN]: Error receiving message.
[20:36:58 WARN]: This error shouldn't appear.
[20:36:58 WARN]: Please check your version or report to dev.
[20:36:58 WARN]: ===============[MQEasy-Runtime-Error]===============
`

Java 16
PaperMC 1.16.5-788
CommandBridge-BungeeCord 1.2.0 
CommandBridge-Spigot 1.2.0 
MQEasy 1.1.4

**Comment by jingwenMC** [comment]
I see.
Will fix soon.

**Comment by jingwenMC** [comment]
This is a bug on CommandBridge, will fix in the next CommandBridge release

**Comment by jingwenMC** [comment]
Fixed on CommandBridge v1.2.1
